[project]
name = "new-repalce-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "genai>=2.1.0",
    "google>=3.0.0",
    "google-genai>=1.50.1",
    "streamlit>=1.51.0",
]
